# Generated by Django 2.0.7 on 2018-09-09 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCPF', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDisciplina', models.CharField(max_length=30)),
                ('descricaoDisciplina', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiraUnidade', models.CharField(max_length=4)),
                ('segundaUnidade', models.CharField(max_length=4)),
                ('terceiraUnidade', models.CharField(max_length=4)),
                ('media', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NDA', 'Qualquer Outro')], max_length=1)),
                ('dataNascimento', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('email', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cadastros.Pessoa')),
                ('nomeInstituicao', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descricaoDesempenho', models.CharField(max_length=150)),
                ('frequencia', models.CharField(max_length=40)),
            ],
            bases=('cadastros.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cadastros.Pessoa')),
                ('nomeInstituicao', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=20)),
            ],
            bases=('cadastros.pessoa',),
        ),
        migrations.AddField(
            model_name='cpf',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='professor',
            field=models.ManyToManyField(to='cadastros.Professor'),
        ),
    ]
